// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQZyK9uA1NCDkHwXhHXp-QI5Dhfidej5M',
    appId: '1:276647878980:web:53b1176fa993d59fbcb711',
    messagingSenderId: '276647878980',
    projectId: 'jucanet-sportreserve-202-a9ebf',
    authDomain: 'jucanet-sportreserve-202-a9ebf.firebaseapp.com',
    storageBucket: 'jucanet-sportreserve-202-a9ebf.firebasestorage.app',
    measurementId: 'G-53XGPNB09P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1q0hPb8Z5q0Crbvz0G91rWeoMMoZjNuI',
    appId: '1:276647878980:android:431950f77a2c3d19bcb711',
    messagingSenderId: '276647878980',
    projectId: 'jucanet-sportreserve-202-a9ebf',
    storageBucket: 'jucanet-sportreserve-202-a9ebf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbJPMRTFjTSpGQ2XXELt2iIxnhBrTBQy0',
    appId: '1:276647878980:ios:ef752f4e2f46bf8abcb711',
    messagingSenderId: '276647878980',
    projectId: 'jucanet-sportreserve-202-a9ebf',
    storageBucket: 'jucanet-sportreserve-202-a9ebf.firebasestorage.app',
    iosBundleId: 'com.example.sportreserve2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbJPMRTFjTSpGQ2XXELt2iIxnhBrTBQy0',
    appId: '1:276647878980:ios:ef752f4e2f46bf8abcb711',
    messagingSenderId: '276647878980',
    projectId: 'jucanet-sportreserve-202-a9ebf',
    storageBucket: 'jucanet-sportreserve-202-a9ebf.firebasestorage.app',
    iosBundleId: 'com.example.sportreserve2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQZyK9uA1NCDkHwXhHXp-QI5Dhfidej5M',
    appId: '1:276647878980:web:62293ddd005e5841bcb711',
    messagingSenderId: '276647878980',
    projectId: 'jucanet-sportreserve-202-a9ebf',
    authDomain: 'jucanet-sportreserve-202-a9ebf.firebaseapp.com',
    storageBucket: 'jucanet-sportreserve-202-a9ebf.firebasestorage.app',
    measurementId: 'G-L8V687CNCE',
  );
}
